### ISSUE TITLE
Setup github actions to build firmware with 3 baudrates on every release

### ISSUE THREAD

**Issue by eduard-sukharev** [navaismo/Ender-3V3-SE#58]
Currently all the prebuilt firmware binaries are built manually, uploaded as files and stored in Firmware folder.

It's not the best way to distribute firmware. We could leverage the power of github actions to build firmware and just upload artefacts on releases. That would remove manual work done upon each release.

We could reuse existing platformio actions to build:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          silent: true
          verbose: true
          disable-auto-clean: false
```

we would need to figure out how to handle the different baudrate settings for matrix build and upload artifacts.
